version: "3"

services:
   apache:
    image: httpd:alpine
    links:
      - phpfpm
      - db
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    environment:
      - FASTCGI=fcgi://192.168.0.6:9000
    hostname: awesome.dev
    networks:
      static-network:
        ipv4_address: 192.168.0.5

   phpfpm:
    build:
      context: .
      dockerfile: ./conf/php5
      #dockerfile: ./conf/php7
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
      - ./conf/php.ini:/usr/local/etc/php/conf.d/50-setting.ini
    networks:
      static-network:
        ipv4_address: 192.168.0.6

   db:
    image: mysql:latest
    volumes:
      - ./conf/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=123
    networks:
      static-network:
        ipv4_address: 192.168.0.7

networks:
  static-network:
    ipam:
      config:
        - subnet: 192.168.0.0/28