apache:
    image: httpd:alpine
    ports:
        - "80:80"
    links:
        - phpfpm
    volumes:
        - ./public_html:/usr/local/apache2/htdocs/
        - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf

phpfpm:
    image: php:fpm
    volumes:
        - ./public_html:/usr/local/apache2/htdocs/

#mysql:
#  image: mariadb
#  environment:
#    MYSQL_ROOT_PASSWORD: admin