version: "3"

services:
   apache:
    image: httpd:alpine
    ports:
      - "8080:80"
    links:
      - phpfpm
    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
      - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    environment:
      - FASTCGI=fcgi://phpfpm:9000

   phpfpm:
    build:
      context: .
      #dockerfile: ./conf/php5
      dockerfile: ./conf/php7

    volumes:
      - ./public_html:/usr/local/apache2/htdocs/
      - ./conf/php.ini:/usr/local/etc/php/conf.d/50-setting.ini